apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-app
spec:
  replicas: 4
  selector: 
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: cat
        image: sreeragdocker/cat-image:latest
        ports:
        - containerPort: 80
          protocol: TCP
